"""Full immutable Stage/FunkinSprite/Bopper references with actual native group/container paths."""
from pathlib import Path
import re
from nv_character_group_fixture_support import nv_character_group_fixture_files
from test_source_attachment_integration import integration_files
from test_nv_multifield_routes import method
ROOT=Path(__file__).resolve().parents[2]

def nv_stage_fixture_files():
 files=integration_files();files.update(nv_character_group_fixture_files())
 # ScriptGroup source construction only reads nullable game/state identity; no game loop is modeled.
 files['flixel/FlxG.hx']=files['flixel/FlxG.hx'].replace('class FlxG {','class FlxG {public static var game:Dynamic=null;public static var state:Dynamic=null;')
 native=ROOT/'.haxelib/flixel/6,1,2/flixel'
 sprite=files['flixel/FlxSprite.hx']
 sprite=sprite.replace('public var cameras:', 'public var flipX=false;public var flipY=false;public var blend:Dynamic;public var cameras:')
 sprite=sprite.replace('function set_frames(', 'public function set_frames(')
 sprite=sprite.replace('class FlxSprite extends FlxObject {', 'class FlxSprite extends FlxObject {public function getScreenPosition(?p:flixel.math.FlxPoint,?c:flixel.FlxCamera):flixel.math.FlxPoint {if(p==null)p=flixel.math.FlxPoint.get();return p.set(x,y);}public function clone():FlxSprite return new FlxSprite();')
 files['flixel/FlxSprite.hx']=sprite
 basic=files['flixel/FlxBasic.hx'].replace('public var exists=true;', 'public var zIndex=0;public var container:flixel.group.FlxContainer.FlxTypedContainer<FlxBasic>;public var exists=true;')
 basic=basic.replace('public function destroy(){destroyed++;}', 'public function destroy(){destroyed++;if(container!=null)container.remove(this);container=null;}')
 files['flixel/FlxBasic.hx']=basic
 files['flixel/group/FlxContainer.hx']=(native/'group/FlxContainer.hx').read_text(encoding='utf-8')
 group=files['flixel/group/FlxGroup.hx'].replace('public function new(){super();}', 'public function new(maxSize=0){super();this.maxSize=maxSize;}').replace('function onMemberAdd(v:T)', 'public function onMemberAdd(v:T)').replace('function onMemberRemove(v:T)', 'public function onMemberRemove(v:T)')
 files['flixel/group/FlxGroup.hx']=group
 files['flixel/FlxCamera.hx']='package flixel;class FlxCamera {}'
 for path,name in [('flixel/addons/display/FlxTiledSprite','FlxTiledSprite'),('flixel/addons/display/FlxBackdrop','FlxBackdrop'),('flixel/system/FlxBGSprite','FlxBGSprite')]:
  files[path+'.hx']='package '+path.rsplit('/',1)[0].replace('/','.')+';class '+name+' extends flixel.FlxSprite {public function new(){super();}}'
 files['openfl/display/BlendMode.hx']='package openfl.display;abstract BlendMode(String) from String to String {public static inline var NORMAL:BlendMode="normal";public static function fromString(s:String):Null<BlendMode> return s=="add"||s=="normal"?cast s:null;}'
 color=(native/'util/FlxColor.hx').read_text(encoding='utf-8')
 f=files['flixel/util/FlxColor.hx'][:-1]+'public inline function new(v:Int)this=v;public var alphaFloat(get,set):Float;inline function get_alphaFloat()return alpha/255;inline function set_alphaFloat(v:Float):Float {this=(this&0x00FFFFFF)|(Std.int(v*255)<<24);return v;}static var COLOR_REGEX=~/^(0x|#)?([A-Fa-f0-9]{8}|[A-Fa-f0-9]{6})$/;static var colorLookup:Map<String,Int>=["WHITE"=>-1,"BLACK"=>0xFF000000];'+method(color,'public static function fromString(')+'}'
 files['flixel/util/FlxColor.hx']=f
 point=files['flixel/math/FlxPoint.hx'].replace('public static function get(', 'public static function weak(x=0.,y=0.)return get(x,y);public static function get(');point=point.replace('public function copyFrom(', 'public function scale(x:Float,y:Float)return set(this.x*x,this.y*y);public function subtract(p:FlxPoint)return set(x-p.x,y-p.y);public function rotateByDegrees(a:Float){var x0=x;var r=a*Math.PI/180;return set(x0*Math.cos(r)-y*Math.sin(r),x0*Math.sin(r)+y*Math.cos(r));}public function copyFrom(')
 files['flixel/math/FlxPoint.hx']=point
 files['flixel/math/FlxMath.hx']=files['flixel/math/FlxMath.hx'][:-1]+'public static inline var EPSILON=0.0000001;public static function fastSin(a:Float)return Math.sin(a);public static function fastCos(a:Float)return Math.cos(a);}'
 a=files['IconAnimation.hx'].replace('public var onFinish=', 'public var onLoop=new FlxTypedSignal<String->Void>();public var onFinish=')
 a=a.replace('public function clear()', 'public var methodCalls:Array<String>=[];public function findFrameLabelIndices(p:String):Array<Int> return p=="label"?[0]:[];public function addByFrameLabel(n:String,p:String,f:Int,l:Bool,x:Bool,y:Bool):Void {methodCalls.push("prefix:"+p);addByPrefix(n,"A bold",f,l,x,y);}public function addBySymbol(n:String,p:String,f:Int,l:Bool,x:Bool,y:Bool):Void {methodCalls.push("symbol:"+p);addByPrefix(n,"A bold",f,l,x,y);}public function addByFrameLabelIndices(n:String,p:String,i:Array<Int>,f:Int,l:Bool,x:Bool,y:Bool):Void {methodCalls.push("label-indices:"+p+":"+i.join(","));addByIndices(n,"A bold",i,"",f,l,x,y);}public function addBySymbolIndices(n:String,p:String,i:Array<Int>,f:Int,l:Bool,x:Bool,y:Bool):Void {methodCalls.push("symbol-indices:"+p+":"+i.join(","));addByIndices(n,"A bold",i,"",f,l,x,y);}public function addByIndices(n:String,p:String,i:Array<Int>,s:String,f:Int=24,l:Bool=true,x:Bool=false,y:Bool=false):Void add(n,i,f,l,x,y);public function exists(n:String):Bool return _animations.exists(n);public function remove(n:String):Void _animations.remove(n);public function finish():Void {if(curAnim!=null)curAnim.finished=true;}public function stop():Void {if(curAnim!=null)curAnim.stop();}public function pause():Void {if(curAnim!=null)curAnim.paused=true;}public function resume():Void {if(curAnim!=null)curAnim.paused=false;}public function copyFrom(a:IconAnimation):Void {for(n=>v in a._animations)add(n,v.frames,v.frameDuration==0?0:1/v.frameDuration,v.looped,v.flipX,v.flipY);}public function clear()')
 files['IconAnimation.hx']=a
 files['flixel/graphics/FlxGraphic.hx']='package flixel.graphics;class FlxGraphic {public var width:Int;public var height:Int;public var key="atlas.png";public var persist=true;public var bitmap=new FixtureBitmap();public function new(w:Int,h:Int){width=w;height=h;}}class FixtureBitmap {public var disposed=0;public function new(){}public function disposeImage(){disposed++;}}'
 f=files['flixel/graphics/frames/FlxAtlasFrames.hx'].replace('public var frames:', 'public var parent=new flixel.graphics.FlxGraphic(150,150);public var frames:');f=f.replace('public function new(){', 'public function addAtlas(a:FlxAtlasFrames):FlxAtlasFrames {for(f in a.frames)frames.push(f);return this;}public function new(){',1);files['flixel/graphics/frames/FlxAtlasFrames.hx']=f
 files['animate/FlxAnimate.hx']='package animate;import flixel.graphics.frames.FlxAtlasFrames;import animate.FlxAnimateFrames.FlxAnimateSettings;class FlxAnimate extends flixel.FlxSprite {public var skew=flixel.math.FlxPoint.get();public var library:FlxAnimateFrames;public var anim:IconAnimation;public function new(x=0.,y=0.,?g:Dynamic,?s:FlxAnimateSettings){super(x,y);anim=animation;}override public function set_frames(f:Dynamic):Dynamic {library=Std.isOfType(f,FlxAnimateFrames)?cast f:null;return super.set_frames(f);}}'
 files['animate/FlxAnimateFrames.hx']='package animate;import flixel.graphics.frames.FlxAtlasFrames;typedef FlxAnimateSettings={?swfMode:Bool,?cacheOnLoad:Bool,?filterQuality:Dynamic,?onSymbolCreate:Dynamic->Void};class FlxAnimateFrames extends FlxAtlasFrames {public var addedCollections:Array<{dictionary:Map<String,Dynamic>}>=[];public function new(){super();}public function existsSymbol(s:String):Bool return s=="symbol";public static function fromAnimate(path:String,?a:Dynamic,?b:Dynamic,?c:Dynamic,?d:Bool,?e:Dynamic):FlxAtlasFrames return StageIO.current.frame(path);public static function combineAtlas(a:Array<FlxAtlasFrames>):FlxAtlasFrames {if(a.length==0)return null;var f=a[0];for(i in 1...a.length)f=f.addAtlas(a[i]);return f;}}'
 files['flixel/util/FlxTimer.hx']='package flixel.util;class FlxTimer {public var calls=0;public function new(){}public function start(t:Float,c:FlxTimer->Void):FlxTimer {calls++;return this;}public function cancel():Void{}public function destroy():Void{}}'
 files['NightmareVisionPaths.hx']='class NightmareVisionPaths {public var scriptExtensions=["hx","hxs","hscript"];public function exists(p:String):Bool return io.scriptFiles.exists(p);public function getModFolder(p:String,?e:String):String return "fixture";public var root="stage-fixture";public var io:StageIO;public var tempAtlasFramesCache:Map<String,flixel.graphics.frames.FlxAtlasFrames>=[];public function new(io:StageIO)this.io=io;public function fileExists(p:String):Bool return io.animated;public function gpuCachingEnabled():Bool return io.gpu;public function getPath(p:String,?a:Dynamic,?b:Bool):String return p;public function getAtlasFrames(p:String):flixel.graphics.frames.FlxAtlasFrames return io.frame(p);public function getTextureAtlas(p:String):flixel.graphics.frames.FlxAtlasFrames return io.frame(p);public function getMultiAtlas(p:Array<String>):flixel.graphics.frames.FlxAtlasFrames {var a=[];for(k in p){var f=io.frame(k);if(f!=null)a.push(f);}return animate.FlxAnimateFrames.combineAtlas(a);}public function image(p:String):flixel.graphics.FlxGraphic {io.calls.push("image:"+p);return new flixel.graphics.FlxGraphic(150,150);}public function forgetAtlasGraphic(g:flixel.graphics.FlxGraphic):Void {io.calls.push("forget:"+g.key);io.tracked.remove(g.key);for(k=>v in tempAtlasFramesCache)if(v.parent==g)tempAtlasFramesCache.remove(k);}}'
 files['StageIO.hx']='import NightmareVisionStageOwner;import NightmareVisionStageDataSchema;class StageIO {public static var current:StageIO;public var paths:NightmareVisionPaths;public var calls:Array<String>=[];public var tracked:Map<String,flixel.graphics.FlxGraphic>=[];public var animated=false;public var gpu=false;public var empty=false;public var active=true;public var frames:flixel.graphics.frames.FlxAtlasFrames;public var data:NightmareVisionStageFile;public var source:String;public var scriptFiles:Map<String,Bool>=[];public var shared:Map<String,Dynamic>;public var loaded:NightmareVisionScriptModule;public var warn:Array<String>=[];public function new(){paths=new NightmareVisionPaths(this);data={defaultZoom:.8,boyfriend:[1,2],girlfriend:[3,4],opponent:[5,6]};current=this;}public function frame(p:String):flixel.graphics.frames.FlxAtlasFrames {calls.push("atlas:"+p);if(empty)return null;if(frames==null)frames=animated?new animate.FlxAnimateFrames():new flixel.graphics.frames.FlxAtlasFrames();tracked.set(frames.parent.key,frames.parent);paths.tempAtlasFramesCache.set(haxe.io.Path.withoutExtension(frames.parent.key),frames);return frames;}public function load(p:String,s:Map<String,Dynamic>):NightmareVisionScriptModule {shared=s;loaded=NightmareVisionScriptModule.fromSource(p,source,null,s,function(i){i.variables.set("io",this);},function(n,p,e){});return loaded;}public function owner():NightmareVisionStageOwner return {requireActive:function(){if(!active)throw "captured stage lease released";},paths:paths,stageFile:function(n)return data,template:function()return {defaultZoom:.8,boyfriend:[0,0],girlfriend:[0,0],opponent:[0,0]},antialiasing:function()return false,resolveClass:function(n)return n=="Plain"?Plain:null,createInstance:function(c,a)return Type.createInstance(c,a),setZIndex:function(o,v)o.zIndex=v,setProperty:function(o,n,v){if(n=="bad")throw "property failed";Reflect.setProperty(o,n,v);},warn:function(s)warn.push(s),scriptPath:function(n){calls.push("script:"+n);return n;},scriptExists:function(n)return scriptFiles.exists(n),fromFile:load,bopper:function(s)return null};public function tick():Void calls.push("tick");}class Plain extends flixel.FlxSprite {public var called=0;public function new(){super();}public function tick():Void {called++;StageIO.current.calls.push("tick");}public function explode():Void throw "advanced failure";}'
 files['FNFAssets.hx']='class FNFAssets {public static function getText(p:String):String return StageIO.current.source;}'
 # Full source reference dependency names: one actual module handle, not a fake parser status.
 files['Paths.hx']='class Paths {public static var tempAtlasFramesCache(get,never):Map<String,flixel.graphics.frames.FlxAtlasFrames>;static function get_tempAtlasFramesCache()return StageIO.current.paths.tempAtlasFramesCache;public static function getPath(p:String,?a:Dynamic,?b:Bool):String return p;public static function image(p:String)return StageIO.current.paths.image(p);public static function getAtlasFrames(p:String)return StageIO.current.paths.getAtlasFrames(p);public static function getMultiAtlas(p:Array<String>)return StageIO.current.paths.getMultiAtlas(p);}'
 files['FunkinAssets.hx']='class FunkinAssets {public static var cache(get,never):Dynamic;static function get_cache():Dynamic return {currentTrackedGraphics:StageIO.current.tracked};public static function exists(p:String,?t:Dynamic):Bool return StringTools.endsWith(p,"Animation.json")?StageIO.current.animated:StageIO.current.scriptFiles.exists(p);}'
 files['ClientPrefs.hx']='class ClientPrefs {public static var gpuCaching(get,never):Bool;static function get_gpuCaching()return StageIO.current.gpu;public static var globalAntialiasing=false;}'
 files['MathUtil.hx']='class MathUtil {public static function fastTan(a:Float)return Math.sin(a)/Math.cos(a);}'
 for host,name in [('FunkinSprite','DonorFunkinSprite'),('Bopper','DonorBopper'),('Stage','DonorStage')]:
  d=(ROOT.parent/'fnf_sources/NightmareVision/source/funkin/objects'/(host+'.hx')).read_text(encoding='utf-8');d=re.sub(r'^(package|import)[^\n]*\n','',d,flags=re.M);d=re.sub(r'\bFunkinSprite\b','DonorFunkinSprite',d);d=re.sub(r'\bBopper\b','DonorBopper',d);d=re.sub(r'\bStage\b','DonorStage',d).replace('override function','override public function').replace('public override public','override public');d=d.replace('public var script:Null<FunkinScript>', 'public var script:Null<NightmareVisionScriptModule>');d=d.replace('obj.makeScaledGraphic(1, 1);','NightmareVisionSpriteMethods.makeScaledGraphic(obj,1,1);');d=d.replace('funkin.data.StageData.getTemplateStageFile()', 'StageData.getTemplateStageFile()').replace('FunkinScript.fromFile(scriptFile, null, group?.scriptShareables)', 'FunkinScript.fromFile(scriptFile, group == null ? null : group.sharedFields)').replace('script = FlxDestroyUtil.destroy(script);','script.destroy();script=null;')
  imports='import flixel.FlxSprite;import flixel.FlxBasic;import flixel.FlxCamera;import flixel.math.FlxPoint;import flixel.math.FlxMath;import flixel.graphics.frames.FlxAtlasFrames;import animate.FlxAnimateFrames;import animate.FlxAnimate;import flixel.util.FlxTimer;import flixel.util.FlxSignal.FlxTypedSignal;import flixel.group.FlxContainer.FlxTypedContainer;import flixel.util.FlxColor;import NightmareVisionStageDataSchema.NightmareVisionStageFile as StageFile;import NightmareVisionStageDataSchema.NightmareVisionStageAnimationInfo as AnimationInfo;import NightmareVisionScriptGroup as ScriptGroup;import NightmareVisionScriptModule as FunkinScript;using StringTools;using haxe.io.Path;\n'
  if host=='Stage':imports=imports.replace('import NightmareVisionScriptModule as FunkinScript;', '')
  files[name+'.hx']=imports+'final WARN=0;final TEXT=0;'+d
 files['StageData.hx']='class StageData {public static function getStageFile(n:String)return StageIO.current.data;public static function getTemplateStageFile():NightmareVisionStageDataSchema.NightmareVisionStageFile return {defaultZoom:.8,boyfriend:[0,0],girlfriend:[0,0],opponent:[0,0]};public static function resolveObjectInstance(n:String):Class<Dynamic> return null;}'
 files['FunkinScript.hx']='class FunkinScript {public static function getPath(n:String):String {StageIO.current.calls.push("script:"+n);return n;}public static function fromFile(p:String,s:Map<String,Dynamic>):NightmareVisionScriptModule return StageIO.current.load(p,s);}'
 cool=(ROOT.parent/'fnf_sources/NightmareVision/source/funkin/utils/CoolUtil.hx').read_text(encoding='utf-8')
 files['CoolUtil.hx']='import openfl.display.BlendMode;using StringTools;class CoolUtil {'+method(cool,'public static function correctArray<')+method(cool,'public static function getBlendFromString(').replace('?? NORMAL','?? BlendMode.NORMAL')+'}'
 files['ReflectUtil.hx']='class ReflectUtil {public static function setProperty(o:Dynamic,n:String,v:Dynamic):Void {if(n=="bad")throw "property failed";Reflect.setProperty(o,n,v);}}'
 files['Logger.hx']='class Logger {public static function log(s:String,?l:Dynamic,?p:Bool):Void StageIO.current.warn.push(s);}'
 return files
