"""Typed dependencies and reference methods generated by the immutable donor macro."""
from pathlib import Path
from nv_alphabet_fixture_support import nv_alphabet_fixture_files
from test_nv_multifield_routes import method
ROOT = Path(__file__).resolve().parents[2]

def nv_sprite_macro_fixture_files():
    files = nv_alphabet_fixture_files()
    files.pop('DonorNVAlphabet.hx', None)
    native = ROOT / '.haxelib/flixel/6,1,2/flixel'
    donor = (ROOT.parent / 'fnf_sources/NightmareVision/source/funkin/backend/macro/FlxMacro.hx').read_text(encoding='utf-8')
    build = method(donor, 'public static macro function buildFlxSprite(')
    files['ReferenceNVSpriteMacro.hx'] = '#if macro\nimport haxe.macro.Expr;import haxe.macro.Context;#end\nclass ReferenceNVSpriteMacro {' + build + '}'
    files['funkin/Paths.hx'] = 'package funkin;class Paths {public static var loader:String->flixel.graphics.frames.FlxAtlasFrames;public static function getAtlasFrames(p:String)return loader(p);}'
    color = (native / 'util/FlxColor.hx').read_text(encoding='utf-8')
    channel_methods = ''.join(method(color, name) for name in ['inline function getThis(', 'inline function get_red(', 'inline function get_green(', 'inline function get_blue(', 'inline function get_alpha(', 'public inline function toHexString('])
    files['flixel/util/FlxColor.hx'] = 'package flixel.util;abstract FlxColor(Int) from Int to Int {public static inline var WHITE:Int=-1;public static inline var BLACK:Int=0xFF000000;public var red(get,never):Int;public var green(get,never):Int;public var blue(get,never):Int;public var alpha(get,never):Int;' + channel_methods + '}'
    point = files['flixel/math/FlxPoint.hx']
    point = point.replace('public var x:Float;', 'public var x(default,set):Float;public function set_x(v:Float)return x=v;').replace('public var y:Float;', 'public var y(default,set):Float;public function set_y(v:Float)return y=v;')
    callback = (native / 'math/FlxPoint.hx').read_text(encoding='utf-8').split('class FlxCallbackPoint extends FlxBasePoint', 1)[1]
    callback = 'class FlxCallbackPoint extends FlxPoint' + callback
    callback = callback.replace('override function set_', 'override public function set_')
    files['flixel/math/FlxPoint.hx'] = point + callback
    sprite = files['flixel/FlxSprite.hx']
    sprite = sprite.replace('public var makes=0;', 'public var makes=0;public var hitboxes=0;public var lastKey:String;')
    sprite = sprite.replace('public function makeGraphic(w:Int,h:Int,c:Null<Int>){makes++;', 'public function makeGraphic(w:Int,h:Int,c:Int=-1,unique:Bool=false,?key:String):FlxSprite{lastKey=key;makes++;')
    sprite = sprite.replace('public function makeGraphic(w:Int,h:Int,c:Int=-1,unique:Bool=false,?key:String):FlxSprite{makes++;', 'public function makeGraphic(w:Int,h:Int,c:Int=-1,unique:Bool=false,?key:String):FlxSprite{lastKey=key;makes++;')
    sprite = sprite.replace('public function updateHitbox():Void\n\t{', 'public function updateHitbox():Void\n\t{hitboxes++;')
    files['flixel/FlxSprite.hx'] = sprite
    sg = (native / 'group/FlxSpriteGroup.hx').read_text(encoding='utf-8')
    generated = method(sg, 'override public function makeGraphic(')
    generated += method(sg, 'override function set_frames(').replace('override function', 'override public function').replace('FlxFramesCollection', 'Dynamic')
    # Execute the actual scale callback and FlxCallbackPoint setter dispatch.
    start = sg.index('inline function scaleCallback(')
    generated += sg[start:sg.index(';', start) + 1]
    group = files['flixel/group/FlxSpriteGroup.hx'].replace('super(x,y);}', 'super(x,y);scale=new flixel.math.FlxPoint.FlxCallbackPoint(scaleCallback);scale.set(1,1);}')
    group = group.replace('override public function destroy()', generated + 'override public function destroy()')
    group = group.replace('import flixel.math.FlxMath;', 'import flixel.util.FlxColor;import flixel.math.FlxMath;')
    files['flixel/group/FlxSpriteGroup.hx'] = group
    files['TargetSprite.hx'] = '@:build(NightmareVisionSpriteMacro.build()) class TargetSprite extends flixel.FlxSprite {public function new(){super();}}'
    files['TargetChild.hx'] = '@:build(NightmareVisionSpriteMacro.build()) class TargetChild extends TargetSprite {public function new(){super();}}'
    files['TargetGroup.hx'] = '@:build(NightmareVisionSpriteMacro.build()) class TargetGroup extends flixel.group.FlxSpriteGroup {public function new(){super();}}'
    files['ReferenceSprite.hx'] = '@:build(ReferenceNVSpriteMacro.buildFlxSprite()) class ReferenceSprite extends flixel.FlxSprite {public function new(){super();}}'
    files['ReferenceGroup.hx'] = '@:build(ReferenceNVSpriteMacro.buildFlxSprite()) class ReferenceGroup extends flixel.group.FlxSpriteGroup {public function new(){super();}}'
    files['DestroyOwn.hx'] = '''@:build(NightmareVisionSpriteMacro.build()) class DestroyOwn extends TargetSprite {
public var early=false;public var failure:Dynamic;public var during=false;public function new(){super();}
override public function destroy(){var nested=function(){return;};nested();during=Reflect.field(this,'__nightmareVisionSpriteOwner')!=null;loadFromSheet('teardown','A bold');if(early)return;if(failure!=null)throw failure;super.destroy();}}
'''
    files['DestroyParent.hx'] = 'class DestroyParent extends flixel.FlxSprite {public var failure:Dynamic;public function new(){super();}override public function destroy(){throw failure;}}'
    files['DestroyInherited.hx'] = '@:build(NightmareVisionSpriteMacro.build()) class DestroyInherited extends DestroyParent {public function new(){super();}}'
    files['DestroyAfterSuper.hx'] = '''@:build(NightmareVisionSpriteMacro.build()) class DestroyAfterSuper extends DestroyOwn {public var after=false;public var caught:Dynamic;public function new(){super();}
override public function destroy(){try {super.destroy();} catch(error:Dynamic) {caught=error;loadFromSheet('caught-parent','A bold');}loadFromSheet('after-parent','A bold');after=true;}}
'''
    files['DestroyNestedSuper.hx'] = '''@:build(NightmareVisionSpriteMacro.build()) class DestroyNestedSuper extends DestroyOwn {public var after=false;public function new(){super();}
override public function destroy(){super.destroy();var nested=function(){return 17;};var result=nested();loadFromSheet('after-nested','A bold');after=result==17;}}
'''
    files['DestroyReturnSuper.hx'] = '@:build(NightmareVisionSpriteMacro.build()) class DestroyReturnSuper extends DestroyOwn {public function new(){super();}override public function destroy(){return super.destroy();}}'
    return files
