"""Owner-scoped updates for exactly regenerated Codename character scripts."""
import importlib.util
import json
from pathlib import Path
import shutil
import sys
import tempfile
import unittest
from unittest.mock import patch

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools"))
SPEC = importlib.util.spec_from_file_location(
    "codename_character_refresh_test", ROOT / "tools/refresh_codename_character_scripts.py")
REFRESH = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(REFRESH)

OWNER = "assets/imported_mods/codename-engine-fixture-123"
HEADER = '// Generated by the Codename importer from the donor character XML ("hero").\n'
TAIL = '''    char.addOffset("singLEFT", 4, -7);
    char.antialiasing = true;
    char.noFlip = false;
    char.playAnim("idle");
}
portraitOffset = [0, 0];
dadVar = 4.0;
isPixel = false;
function sing(direction, miss, alt, char) {}
function update(elapsed, char) {}
var danced = false;
function dance(char) {
    char.playAnim("idle");
}
'''


def animate_script():
    return (HEADER + "function init(char) {\n"
            + "    char.loadTextureAtlas(hscriptPath + 'char');\n"
            + '    char.animation.addBySymbol("idle", "Idle", 24, false);\n'
            + '    char.animation.addBySymbolIndices("singLEFT", "Left", [0,2], 30, true);\n'
            + TAIL).encode()


def old_script(name="hero"):
    header = HEADER.replace('"hero"', '"' + name + '"')
    return (header + "function init(char) {\n"
            + "    char.frames = FlxAtlasFrames.fromSparrow(hscriptPath + 'char.png', hscriptPath + 'char.xml');\n"
            + '    char.animation.addByPrefix("idle", "Idle", 24, false);\n'
            + '    char.animation.addByIndices("singLEFT", "Left", [0,2], \'\', 30, true);\n'
            + TAIL).encode()


def multipage_script():
    return (HEADER.replace('"hero"', '"pages"') + "function init(char) {\n"
            + "    char.frames = FlxAtlasFrames.fromSparrow(hscriptPath + 'char/1.png', hscriptPath + 'char/1.xml');\n"
            + '    char.frames.addAtlas(FlxAtlasFrames.fromSparrow(hscriptPath + "char/2.png", hscriptPath + "char/2.xml"));\n'
            + '    char.animation.addByPrefix("idle", "Idle", 24, false);\n'
            + '    char.animation.addByIndices("singLEFT", "Left", [0,2], \'\', 30, true);\n'
            + TAIL).encode()


class CodenameCharacterScriptRefreshTest(unittest.TestCase):
    def setUp(self):
        self.scratch = tempfile.TemporaryDirectory(dir=ROOT / "tmp")
        self.addCleanup(self.scratch.cleanup)
        self.work = Path(self.scratch.name)
        self.runtime, self.preview = self.work / "runtime", self.work / "preview"
        self.locks = self.work / "locks"
        self.locks.mkdir()
        for setting in (patch.object(REFRESH, "LOCK_ROOT", self.locks),
                        patch.object(REFRESH, "TMP", self.work)):
            setting.start()
            self.addCleanup(setting.stop)
        self.plan_path = self.work / "review.json"
        for root in (self.runtime, self.preview):
            assets = root / "assets/data/fixture"
            assets.mkdir(parents=True)
            (assets / "compatScripts.json").write_text(json.dumps({
                "version": 1, "selectedRoot": OWNER,
                "roots": [{"path": OWNER, "engine": "Codename Engine"}],
            }))
            (assets / "fixture-hard.json").write_text('{"song":{"keep":true}}')
        self._pair("hero", old_script(), animate_script(), "animate")
        self._pair("pages", old_script("pages"), multipage_script(), "pages")
        self._pair("custom", b"function init(char) { char.x = 1; }\n",
                   b"function init(char) { char.x = 2; }\n", "animate")
        edited_new = animate_script()
        edited_old = old_script().replace(b'char.addOffset("singLEFT", 4, -7);',
                                          b'char.addOffset("singLEFT", 99, -7);')
        self._pair("edited", edited_old, edited_new, "animate")
        self.global_script = self.runtime / "assets/images/custom_chars/custom.hscript"
        self.global_script.parent.mkdir(parents=True)
        self.global_script.write_bytes(b"global custom script\n")

    def _pair(self, name, old_script_bytes, new_script_bytes, asset_mode):
        for root, script in ((self.runtime, old_script_bytes), (self.preview, new_script_bytes)):
            owner = root / OWNER
            chars = owner / "images/custom_chars"
            chars.mkdir(parents=True, exist_ok=True)
            (chars / (name + ".hscript")).write_bytes(script)
            folder = chars / name
            if asset_mode == "animate":
                atlas = folder / "char"
                atlas.mkdir(parents=True)
                (atlas / "Animation.json").write_text('{"name":"fixture"}')
                (atlas / "spritemap1.json").write_text('{"width":1}')
                (atlas / "spritemap1.png").write_bytes(b"identical sprite page")
            else:
                atlas = folder / "char"
                atlas.mkdir(parents=True)
                for page in (1, 2):
                    (atlas / f"{page}.png").write_bytes(f"page-{page}".encode())
                    (atlas / f"{page}.xml").write_text(f"<TextureAtlas page='{page}'/>")

    def plan(self):
        plan = REFRESH.make_plan(self.runtime, self.preview, OWNER)
        self.plan_path.write_text(json.dumps(plan))
        return plan

    def test_only_exact_generated_transforms_with_matching_owner_assets_are_planned(self):
        plan = self.plan()
        self.assertEqual([item["id"] for item in plan["candidates"]], [
            "images/custom_chars/hero.hscript", "images/custom_chars/pages.hscript"])
        reasons = {item["id"]: item["reason"] for item in plan["skipped"]}
        self.assertIn("not an importer-generated", reasons["images/custom_chars/custom.hscript"])
        self.assertIn("edits beyond the importer transform",
                      reasons["images/custom_chars/edited.hscript"])

    def test_apply_backups_only_owner_scripts_and_preserves_other_files(self):
        plan = self.plan()
        old_hero = (self.runtime / OWNER / "images/custom_chars/hero.hscript").read_bytes()
        data = self.runtime / "assets/data/fixture/fixture-hard.json"
        old_data = data.read_bytes()
        custom = self.runtime / OWNER / "images/custom_chars/custom.hscript"
        old_custom = custom.read_bytes()
        backup = REFRESH.apply_plan(plan, self.plan_path)
        self.assertIsNotNone(backup)
        saved = backup / (OWNER + "/images/custom_chars/hero.hscript")
        self.assertEqual(saved.read_bytes(), old_hero)
        self.assertEqual((self.runtime / OWNER / "images/custom_chars/hero.hscript").read_bytes(),
                         animate_script())
        self.assertEqual((self.runtime / OWNER / "images/custom_chars/pages.hscript").read_bytes(),
                         multipage_script())
        self.assertEqual(custom.read_bytes(), old_custom)
        self.assertEqual(self.global_script.read_bytes(), b"global custom script\n")
        self.assertEqual(data.read_bytes(), old_data)
        self.assertEqual(self.plan()["candidates"], [])

    def test_assets_must_match_and_changes_after_review_abort_apply(self):
        plan = self.plan()
        page = self.preview / OWNER / "images/custom_chars/hero/char/spritemap1.png"
        page.write_bytes(b"different")
        current = self.runtime / OWNER / "images/custom_chars/hero.hscript"
        before = current.read_bytes()
        with self.assertRaisesRegex(ValueError, "changed since review"):
            REFRESH.apply_plan(plan, self.plan_path)
        self.assertEqual(current.read_bytes(), before)
        self.assertIn("required owner atlas asset differs",
                      {item["id"]: item["reason"] for item in
                       REFRESH.make_plan(self.runtime, self.preview, OWNER)["skipped"]}
                      ["images/custom_chars/hero.hscript"])

    def test_owner_must_be_selected_by_both_runtimes(self):
        manifest = self.preview / "assets/data/fixture/compatScripts.json"
        manifest.write_text(json.dumps({"version": 1, "selectedRoot": "assets/imported_mods/other-123",
            "roots": [{"path": "assets/imported_mods/other-123", "engine": "Codename Engine"}]}))
        with self.assertRaisesRegex(ValueError, "no selected Codename songs"):
            REFRESH.make_plan(self.runtime, self.preview, OWNER)

    def test_runtime_lock_and_replace_failure_preserve_backups_and_old_scripts(self):
        plan = self.plan()
        targets = [self.runtime / OWNER / item["id"] for item in plan["candidates"]]
        before = [path.read_bytes() for path in targets]
        with (self.locks / "runtime-0.lock").open("a+") as lock:
            import fcntl
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
            with self.assertRaises(BlockingIOError):
                REFRESH.apply_plan(plan, self.plan_path)
        original_replace = REFRESH.os.replace
        replacements = 0

        def fail_second(source, target):
            nonlocal replacements
            replacements += 1
            if replacements == 2:
                raise OSError("replace failed")
            return original_replace(source, target)

        with patch.object(REFRESH.os, "replace", side_effect=fail_second):
            with self.assertRaisesRegex(OSError, "replace failed"):
                REFRESH.apply_plan(plan, self.plan_path)
        self.assertEqual([path.read_bytes() for path in targets], before)
        self.assertEqual(list(self.work.glob(".codename-char-refresh-*")), [])
        self.assertEqual(len(list((self.work / "import-refresh-backups").iterdir())), 1)


if __name__ == "__main__":
    unittest.main()
