#!/usr/bin/env python3
"""Plan/apply a reviewed refresh of generated Codename character scripts.

Only importer-generated scripts whose old/new difference is the recognized
Sparrow/Animate atlas and animation-registration transform are eligible. The
selected imported owner and its required character atlas assets must match
between the installed runtime and isolated preview. Other files are untouched.
"""

import argparse
import base64
from datetime import datetime, timezone
try:
    from tools import file_lock as fcntl
except ModuleNotFoundError:
    import file_lock as fcntl  # Direct python tools/<script>.py invocation.
import hashlib
import json
import os
from pathlib import Path, PurePosixPath
import re
import shutil
import tempfile

import refresh_codename_events as shared


ROOT = Path(__file__).resolve().parents[1]
TMP = ROOT / "tmp"
LOCK_ROOT = ROOT / ".tools"
OWNER_PREFIX = "assets/imported_mods/"
CHARACTERS = "images/custom_chars"

_STRING = r"(?:'[^'\\]*'|\"(?:\\.|[^\"\\])*\")"
_ANIMATION_PREFIX = re.compile(
    rf'^    char\.animation\.addBy(Prefix|Symbol)\(({_STRING}), ({_STRING}), (\d+), (true|false)\);$')
_ANIMATION_INDICES = re.compile(
    rf'^    char\.animation\.addBy(Indices|SymbolIndices)\(({_STRING}), ({_STRING}), '
    r'\[([-\d, ]*)\], (?:\'\', )?(\d+), (true|false)\);$')
_SPARROW_SETUP = re.compile(
    rf'^    char\.frames = FlxAtlasFrames\.fromSparrow\(hscriptPath \+ ({_STRING}), '
    rf'hscriptPath \+ ({_STRING})\);$')
_SPARROW_ADD_ATLAS = re.compile(
    rf'^    char\.frames\.addAtlas\(FlxAtlasFrames\.fromSparrow\(hscriptPath \+ ({_STRING}), '
    rf'hscriptPath \+ ({_STRING})\)\);$')
_GENERATED_HEADER = re.compile(
    r'^// Generated by the Codename importer from the donor character XML \(".*"\)\.$')


def digest(data):
    return hashlib.sha256(data).hexdigest()


def fingerprint():
    return {
        "tools/refresh_codename_character_scripts.py": digest(Path(__file__).read_bytes()),
        "tools/refresh_codename_events.py": digest((ROOT / "tools/refresh_codename_events.py").read_bytes()),
    }


def decode_string(value):
    if value.startswith("'") and value.endswith("'"):
        return value[1:-1]
    if value.startswith('"') and value.endswith('"'):
        return json.loads(value)
    raise ValueError("invalid generated HScript string")


def animation_signature(line):
    match = _ANIMATION_PREFIX.fullmatch(line)
    if match:
        method, name, symbol, fps, loop = match.groups()
        return ("prefix", decode_string(name), decode_string(symbol), int(fps), loop == "true")
    match = _ANIMATION_INDICES.fullmatch(line)
    if match:
        method, name, symbol, values, fps, loop = match.groups()
        indices = tuple(int(value.strip()) for value in values.split(",") if value.strip())
        return ("indices", decode_string(name), decode_string(symbol), indices,
                int(fps), loop == "true")
    return None


def safe_atlas_path(value):
    path = PurePosixPath(value)
    return (not path.is_absolute() and "\\" not in value and "\0" not in value
            and all(part not in ("", ".", "..") for part in path.parts))


def sparrow_pair(png, xml):
    if not safe_atlas_path(png) or not safe_atlas_path(xml):
        raise ValueError("unsafe generated Sparrow atlas path")
    if not png.endswith(".png") or xml != png[:-4] + ".xml":
        raise ValueError("generated Sparrow atlas pages do not match")
    if png not in ("char.png",) and not re.fullmatch(r"char/[1-9]\d*\.png", png):
        raise ValueError("unexpected generated Sparrow atlas path")
    return png, xml


def atlas_setup(lines):
    """Return (consumed lines, descriptor) for the exact importer setup forms."""
    if len(lines) < 3:
        raise ValueError("generated character script is incomplete")
    animate = "    char.loadTextureAtlas(hscriptPath + 'char');"
    if lines[2] == animate:
        return 1, {"mode": "animate", "directory": "char"}

    match = _SPARROW_SETUP.fullmatch(lines[2])
    if not match:
        raise ValueError("unrecognized generated character atlas setup")
    pair = sparrow_pair(*(decode_string(value) for value in match.groups()))
    pages = [pair]
    consumed = 1
    while 2 + consumed < len(lines):
        match = _SPARROW_ADD_ATLAS.fullmatch(lines[2 + consumed])
        if not match:
            break
        pages.append(sparrow_pair(*(decode_string(value) for value in match.groups())))
        consumed += 1
    if pages[0][0] == "char.png":
        if len(pages) != 1:
            raise ValueError("classic Sparrow setup cannot append pages")
    else:
        expected = [f"char/{index}.png" for index in range(1, len(pages) + 1)]
        if [page[0] for page in pages] != expected:
            raise ValueError("generated Sparrow atlas pages are not contiguous")
    return consumed, {"mode": "sparrow", "pages": pages}


def generated_signature(data):
    try:
        text = data.decode("utf-8")
    except UnicodeDecodeError as error:
        raise ValueError("generated character script is not UTF-8") from error
    lines = text.splitlines()
    if (len(lines) < 4 or not _GENERATED_HEADER.fullmatch(lines[0])
            or lines[1] != "function init(char) {"):
        raise ValueError("script is not an importer-generated character implementation")
    setup_count, atlas = atlas_setup(lines)
    operations = []
    animations = []
    for line in lines[2 + setup_count:]:
        signature = animation_signature(line)
        if signature is None:
            operations.append(("line", line))
        else:
            animations.append(signature)
            operations.append(("animation", signature))
    if not animations:
        raise ValueError("generated character script has no animation registrations")
    return (tuple(lines[:2]), tuple(operations), atlas)


def transform_matches(installed, generated):
    """Accept only the atlas/registration API rewrite; all other lines must match."""
    old_header, old_body, old_atlas = generated_signature(installed)
    new_header, new_body, new_atlas = generated_signature(generated)
    if old_header != new_header or old_body != new_body:
        raise ValueError("installed generated script has edits beyond the importer transform")
    if old_atlas.get("mode") != "sparrow" or old_atlas.get("pages") != [("char.png", "char.xml")]:
        raise ValueError("installed script is not the recognized single-atlas importer output")
    if new_atlas.get("mode") not in ("animate", "sparrow"):
        raise ValueError("preview uses an unsupported generated atlas format")
    return new_atlas


def safe_directory(path, root):
    return (path.is_dir() and not path.is_symlink() and shared.within(path, root))


def atlas_assets(character_root, descriptor):
    if descriptor["mode"] == "animate":
        atlas_dir = character_root / descriptor["directory"]
        if not atlas_dir.is_dir() or atlas_dir.is_symlink():
            raise ValueError("missing owner Animate atlas directory")
        if not (atlas_dir / "Animation.json").is_file():
            raise ValueError("owner Animate atlas lacks Animation.json")
        found = []
        for path in sorted(atlas_dir.rglob("*")):
            if path.is_symlink():
                raise ValueError("owner Animate atlas contains a symlink")
            if path.is_file():
                if not shared.within(path, character_root):
                    raise ValueError("owner Animate atlas escaped its character directory")
                found.append(path.relative_to(character_root).as_posix())
        if not any(PurePosixPath(path).suffix.lower() in (".png", ".webp") for path in found):
            raise ValueError("owner Animate atlas has no sprite page")
        return found
    return sorted({asset for png, xml in descriptor["pages"] for asset in (png, xml)})


def matching_atlas_inputs(runtime_character, preview_character, descriptor):
    runtime_assets = atlas_assets(runtime_character, descriptor)
    preview_assets = atlas_assets(preview_character, descriptor)
    if runtime_assets != preview_assets:
        raise ValueError("required owner atlas file set differs")
    hashes = {}
    for relative in runtime_assets:
        old = runtime_character / relative
        fresh = preview_character / relative
        for path, base in ((old, runtime_character), (fresh, preview_character)):
            if (not path.is_file() or path.is_symlink() or not shared.within(path, base)):
                raise ValueError("missing or unsafe required owner atlas asset: " + relative)
        old_hash, fresh_hash = digest(old.read_bytes()), digest(fresh.read_bytes())
        if old_hash != fresh_hash:
            raise ValueError("required owner atlas asset differs: " + relative)
        hashes[old.as_posix()] = old_hash
        hashes[fresh.as_posix()] = fresh_hash
    return hashes


def owner_path(value):
    if (not isinstance(value, str) or not value.startswith(OWNER_PREFIX)
            or len(value.split("/")) != 3 or not shared.safe_segment(value.split("/")[-1])):
        raise ValueError("owner must be an assets/imported_mods/<safe-id> path")
    return value


def selected_owner_manifests(runtime, owner):
    manifests = [manifest for _, manifest in shared.selected_songs(runtime, owner)]
    if not manifests:
        raise ValueError("runtime has no selected Codename songs for this owner")
    return manifests


def make_plan(runtime_root, generated_root, owner):
    runtime, preview = runtime_root.resolve(), generated_root.resolve()
    owner = owner_path(owner)
    if (runtime == preview or shared.within(runtime, preview) or not shared.within(preview, TMP)
            or not (runtime / "assets/data").is_dir() or not (preview / "assets/data").is_dir()):
        raise ValueError("preview must be a separate repository-local tmp runtime")
    runtime_owner, preview_owner = runtime / owner, preview / owner
    for path, base in ((runtime_owner, runtime), (preview_owner, preview)):
        if not safe_directory(path, base):
            raise ValueError("missing or unsafe imported owner root")
    runtime_manifests = selected_owner_manifests(runtime, owner)
    preview_manifests = selected_owner_manifests(preview, owner)
    runtime_chars = runtime_owner / CHARACTERS
    preview_chars = preview_owner / CHARACTERS
    if not safe_directory(runtime_chars, runtime_owner) or not safe_directory(preview_chars, preview_owner):
        raise ValueError("missing or unsafe imported custom-character directory")

    inputs = {}
    for path in runtime_manifests + preview_manifests:
        inputs[path.as_posix()] = digest(path.read_bytes())
    candidates, skipped = [], []
    for installed in sorted(runtime_chars.glob("*.hscript")):
        relative = installed.relative_to(runtime_owner)
        fresh = preview_owner / relative
        if installed.is_symlink() or not installed.is_file() or not shared.within(installed, runtime_owner):
            skipped.append({"id": relative.as_posix(), "reason": "unsafe installed script"})
            continue
        if not fresh.is_file() or fresh.is_symlink() or not shared.within(fresh, preview_owner):
            skipped.append({"id": relative.as_posix(), "reason": "preview script missing or unsafe"})
            continue
        old_bytes, new_bytes = installed.read_bytes(), fresh.read_bytes()
        if old_bytes == new_bytes:
            continue
        try:
            descriptor = transform_matches(old_bytes, new_bytes)
            old_character = installed.parent / installed.stem
            fresh_character = fresh.parent / fresh.stem
            if (not safe_directory(old_character, runtime_owner)
                    or not safe_directory(fresh_character, preview_owner)):
                raise ValueError("missing or unsafe owner character bundle")
            inputs.update(matching_atlas_inputs(old_character, fresh_character, descriptor))
            inputs[installed.as_posix()] = digest(old_bytes)
            inputs[fresh.as_posix()] = digest(new_bytes)
        except (ValueError, OSError, TypeError) as error:
            skipped.append({"id": relative.as_posix(), "reason": str(error)})
            continue
        candidates.append({"id": relative.as_posix(), "target": installed.as_posix(),
                           "beforeSha256": digest(old_bytes), "afterSha256": digest(new_bytes),
                           "afterBase64": base64.b64encode(new_bytes).decode("ascii")})
    return {"version": 1, "owner": owner, "runtimeRoot": runtime.as_posix(),
            "generatedRoot": preview.as_posix(), "toolSha256": fingerprint(),
            "inputsSha256": inputs, "candidates": candidates, "skipped": skipped}


def apply_plan(plan, plan_path):
    plan_path = plan_path.resolve()
    if not shared.within(plan_path, TMP) or not plan_path.is_file() or plan_path.is_symlink():
        raise ValueError("plan must be a repository-local tmp file")
    if plan.get("version") != 1 or plan.get("toolSha256") != fingerprint():
        raise ValueError("refresh implementation changed since review")
    runtime, preview = Path(plan["runtimeRoot"]).resolve(), Path(plan["generatedRoot"]).resolve()
    locks = []
    try:
        for mode in ("0", "1"):
            lock = (LOCK_ROOT / ("runtime-" + mode + ".lock")).open("a+")
            locks.append(lock)
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        fresh = make_plan(runtime, preview, plan.get("owner"))
        if fresh != plan:
            raise ValueError("owner scripts or required assets changed since review")
        if not plan["candidates"]:
            return None

        backup = TMP / "import-refresh-backups" / datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%S%fZ")
        backup.mkdir(parents=True, exist_ok=False)
        shutil.copy2(plan_path, backup / "plan.json")
        for item in plan["candidates"]:
            target = Path(item["target"])
            if (not shared.within(target, runtime / plan["owner"])
                    or digest(target.read_bytes()) != item["beforeSha256"]):
                raise ValueError("unsafe or changed generated script: " + item["id"])
            saved = backup / target.relative_to(runtime)
            saved.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(target, saved)
            if digest(saved.read_bytes()) != item["beforeSha256"]:
                raise ValueError("backup verification failed: " + item["id"])

        replaced = []
        try:
            for item in plan["candidates"]:
                target = Path(item["target"])
                output = base64.b64decode(item["afterBase64"], validate=True)
                if digest(output) != item["afterSha256"]:
                    raise ValueError("planned generated script hash mismatch: " + item["id"])
                with tempfile.NamedTemporaryFile(dir=target.parent, prefix=".codename-char-refresh-",
                                                 delete=False) as stage:
                    stage.write(output)
                    stage.flush()
                    os.fsync(stage.fileno())
                    staged = Path(stage.name)
                try:
                    os.chmod(staged, target.stat().st_mode)
                    os.replace(staged, target)
                finally:
                    staged.unlink(missing_ok=True)
                replaced.append(target)
        except Exception:
            for target in replaced:
                shutil.copy2(backup / target.relative_to(runtime), target)
            raise
        return backup
    finally:
        for lock in reversed(locks):
            lock.close()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    planning = commands.add_parser("plan")
    planning.add_argument("--runtime-root", type=Path, required=True)
    planning.add_argument("--generated-root", type=Path, required=True)
    planning.add_argument("--owner", required=True,
                          help="selected imported owner path, assets/imported_mods/<id>")
    planning.add_argument("--output", type=Path, required=True)
    applying = commands.add_parser("apply")
    applying.add_argument("--plan", type=Path, required=True)
    args = parser.parse_args()
    if args.command == "plan":
        if args.output.exists() or not shared.within(args.output, TMP):
            parser.error("output must be a new repository-local tmp file")
        try:
            plan = make_plan(args.runtime_root, args.generated_root, args.owner)
        except ValueError as error:
            parser.error(str(error))
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(json.dumps(plan, indent=2) + "\n")
        print("plan: %s; candidates=%d skipped=%d" %
              (args.output, len(plan["candidates"]), len(plan["skipped"])))
    else:
        plan = json.loads(args.plan.read_text())
        backup = apply_plan(plan, args.plan)
        print("applied; backup: " + backup.as_posix() if backup else "no changes in plan")


if __name__ == "__main__":
    main()
